name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: pnpm install

      - name: Lint Addon
        run: pnpm lint
        working-directory: addon

      - name: Lint Test App
        run: pnpm lint
        working-directory: test-app

      - name: Test
        run: pnpm test:ember
        working-directory: test-app
