name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --no-lockfile

      - run: yarn lint

      - run: yarn test
